### ISSUE TITLE
[DOC] SLIXLineplotParameterGenerator example

### ISSUE THREAD

**Issue by matteomancini** [3d-pli/SLIX#10]
#Is it possible to add an example for SLIXLineplotParameterGenerator (even a very brief one) based on one of the two datasets used for SLIXParameterGenerator and providing a text file with intensity values? This would make easier to try out that specific functionality.

https://github.com/openjournals/joss-reviews/issues/2675

**Comment by Thyre** [comment]
I absolutely agree that we should include one or two examples for `SLIXLineplotParameterGenerator` in the README.md. I've added two example files in [10-SLIXLineplotParameterGenerator-example](https://github.com/3d-pli/SLIX/tree/10-SLIXLineplotParameterGenerator-example). The README.md is still in progress but will contain both instructions on how to use `SLIXLineplotParameterGenerator` and what results are being generated when running the program for the given examples (see [update-readme](https://github.com/3d-pli/SLIX/tree/update-readme)).

**Comment by miriammenzel** [comment]
I have updated the [README.md](https://github.com/3d-pli/SLIX/blob/master/README.md) with a more detailed explanation and an example of how to use `SLIXLineplotParameterGenerator` in the Section "Evaluation of Line Profiles". Please let us know if we should add anything else there.

**Comment by miriammenzel** [comment]
@matteomancini: Please let us know if we can close this issue.

**Comment by matteomancini** [comment]
I think it looks great, it is clear and immediate to reproduce!
