### ISSUE TITLE
[DOC] Contributor Guidelines

### ISSUE THREAD

**Issue by alexrockhill** [3d-pli/SLIX#5]
According to JOSS policy, contribution guidelines are requested to be written.

<img width="487" alt="Screen Shot 2020-10-12 at 4 06 59 PM" src="https://user-images.githubusercontent.com/13473576/95797684-f6d11700-0ca4-11eb-840c-14b81d283118.png">

https://github.com/openjournals/joss-reviews/issues/2675

**Comment by Thyre** [comment]
I've added a first version of the contribution guidelines [here](https://github.com/3d-pli/SLIX/blob/master/CONTRIBUTING.md)
Is there a section missing in the document or is it okay?

**Comment by alexrockhill** [comment]
That seems to me to check all the boxes, thanks
